### ISSUE TITLE
string keys need to be adjusted

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#11]
Related to #2 (code review) and this checklist item:

> - [ ]  Make sure the string keys are all perfect, because they are difficult to change after 1.0.0 is published. Guidelines for string keys are:
> 
> (1) Strings keys should generally match their values. E.g.:
> 
```js
"helloWorld": {
  value: "Hello World!"
},
"quadraticTerms": {
  value: "Quadratic Terms"
}
```

This sim currently uses nested string keys, and keys containing hypens.  Nested keys are sometimes used in common-code repositories (to group strings), but not in sim repositories.    And we typically use camel case instead of hyphens.

For example:

```js
  "amp-selector-1d.normal-mode": {
    "value": "Normal Mode: "
  },
```

... should simply to:

```js
  "normalMode": {
    "value": "Normal Mode: "
  },
```

**Comment by pixelzoom** [comment]
String keys were adjusted in the above commit. Ready for review.

**Comment by Hyodar** [comment]
Understood! Thanks for adjusting.
I'll go ahead and close the issue.
