### ISSUE TITLE
use string pattern for omega values

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#12]
Related to #2 (code review). 

For this view:

<img width="419" alt="screenshot_107" src="https://user-images.githubusercontent.com/3046552/74077681-00500400-49df-11ea-9ef6-7b77da825339.png">

The omega symbols and their coefficients are put together using string concatenation. See AmpPhaseAccordionBox:

```js
165          `${freq.toFixed( 2 )}\u03C9\u2080`,
````

This should be using a translatable string pattern like:

```js
  "omegaPattern": {
    "value": "{{value}} \u03C9\u2080"
  },
 ```
... and `StringUtils.fillIn` to fill in the value.  E.g.:

```js
const omegaPattern = require( 'string!NORMAL_MODES/omegaPattern' );
...
StringUtils.fillIn( omegaPattern, {
  value: freq.toFixed( 2 )
} );
```

**Comment by Hyodar** [comment]
Added a string pattern for the omega values. Everything seems ok, it also passed the `stringTest=X` from #10.
Also, is there any naming convention for those? On masses and springs simulation, for example, the patterns are named just like normal strings, whereas your example adds `Pattern` to the end and the require constant doesn't have `String`.
Do you have any suggestions on how I should name both the string and the require constant?

**Comment by pixelzoom** [comment]
The `const` must be the same as the string key, with "String" suffix added.   There's a lint rule that checks this and will fail if the convention is not followed.   So for example:

```js
// lint rule passes
const someKeyString = require( 'string!NORMAL_MODES/someKey' );

// lint rule fails
const someKey = require( 'string!NORMAL_MODES/someKey' );
```

Unfortunately, there's no standardization for the "key" for pattern strings.  I have typically used the "Pattern" suffix. But there's no enforcement (or even requirement) for this.  I have also used the name of the value to be filled in as part of the key.  I would have used "frequencyRation" where you used "frequency", so that the resulting code looks like:

```js
        StringUtils.fillIn( frequencyRatioOmegaPatternString, {
            frequencyRatio: Utils.toFixed( frequencyRatio, 2 )
          } )
```

But what you've done here so far is fine.  It's up to you whether you want to change anything.

**Comment by Hyodar** [comment]
All right. I was unsure whether to name it `frequencyOmegaPatternString`, following the UI, or `frequencyRatioOmegaPatternString`, as its value to fill in is, in fact, a frequency ratio. On second thought, the latter looks better.
Thanks!

**Comment by Hyodar** [comment]
It looks ok now, so I'll close it.
