### ISSUE TITLE
assertion failures: strings with trailing spaces

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#13]
Related to #2 (code review).  When running with `?ea`, the sim experiences multiple assertion failures related to translated string values that have trailing spaces. E.g.:

> Assertion failed: String should not have trailing or leading whitespace, key: numberOfMasses, value: "Number of Masses: "

**Comment by pixelzoom** [comment]
Multiple string values were fixed in the above commit.

**Comment by Hyodar** [comment]
Understood!
Since it's already fixed and ready for review, I'll just close the issue.
