### ISSUE TITLE
assertion failure: matrix should not map plane to a line or point

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#14]
Related to #2 (code review).  When running with `?ea`:

> assert.js?bust=1581129055634:22 Uncaught Error: Assertion failed: matrix should not map plane to a line or point
window.assertions.assertFunction	@	assert.js?bust=1581129055634:22
appendMatrix	@	Node.js?bust=1581129055716:2295
scale	@	Node.js?bust=1581129055716:2041
scale	@	Node.js?bust=1581129055716:2029
(anonymous)	@	Node.js?bust=1581129055716:4985
u	@	lodash-4.17.4.min.js…ust=1581129055716:5
ru	@	lodash-4.17.4.min.js…st=1581129055716:67
mutate	@	Node.js?bust=1581129055716:4975
Node	@	Node.js?bust=1581129055716:527
NumberDisplay	@	NumberDisplay.js?bust=1581129055716:169
NumberControl	@	NumberControl.js?bust=1581129055716:237
OptionsPanel	@	OptionsPanel.js?bust=1581129055716:232
OneDimensionScreenView	@	OneDimensionScreenVi…st=1581129055716:71
(anonymous)	@	OneDimensionScreen.j…st=1581129055716:36
initializeView	@	Screen.js?bust=1581129055716:266
(anonymous)	@	Sim.js?bust=1581129055716:866
(anonymous)	@	Sim.js?bust=1581129055716:874
setTimeout (async)

**Comment by pixelzoom** [comment]
The failure is occurring at OptionsPanel.js line 228:

```
        numberDisplayOptions: {
228      scale: 0
        }
```

Apparently the speed control is a NumberControl, and this is an attempt to hide the associated NumberDisplay (and keep it from contributing to bounds?)   The proper way to do that would be a custom `layoutFunction` for the NumberControl.  And this should most definitely not be a NumberControl (see #42).

I'm going to change `scale: 0` to `visible: false` for now, to get past this error.

**Comment by pixelzoom** [comment]
This same approach is used in AmpPhaseAccordionBox in `ampSliderOptions` and `phaseSliderOptions`.  In this case, they don't want the title or NumberDisplay, and are setting `scale: 0` for both.  This results in the same error.   Again, the correct approach is a custom `layoutFunction` that excludes the title and NumberDisplay.

**Comment by pixelzoom** [comment]
As it turns out AmpPhaseAccordionBox is creating a NumberControl with no title, no NumberDisplay, and no arrow buttons.  So it's only the slider.   And we needs a VSlider, which isn't supported by NumberControl (see #16).  So the solution to this and #16 is to replace NumberControl with VSlider - which I've done in the above commits. 

This is ready for review.  The lessons to be learned here are:
(1) When to use NumberControl
(2) When to write your own layoutFunction for NumberControl
(3) Never attempt to hide a Node by setting `scale: 0`

**Comment by Hyodar** [comment]
Hahaha, that's right: 'A little knowledge is a dangerous thing'.

Well, I think these lessons are already pretty clear now, so I'll go ahead and close the issue :)
