### ISSUE TITLE
replace toFixed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#18]
Related to #2 (code review). 

> - [ ] `DOT/Utils.toFixed` or `DOT/Utils.toFixedNumber` should be used instead of `toFixed`. JavaScript's `toFixed` is notoriously buggy. Behavior differs depending on browser, because the spec doesn't specify whether to round or floor.

The sim uses `toFixed` where it should use `DOT/Utils` `toFixed` or `toFixedNumber`.  See 2 occurrences in AmpPhaseAccordionBox.js.

**Comment by Hyodar** [comment]
Replaced `toFixed` with `Utils.toFixed`. There was no need to return it as a number, so `Utils.toFixed` was fine.

**Comment by Hyodar** [comment]
About these strings, there's still #12 to solve, but the `toFixed` usage now seems fine, so I'll go ahead and close this issue.
