### ISSUE TITLE
convert from inherit to class

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#21]
Related to #2 (code review):

> - [ ] Use `class` and `extends` for defining classes and implementing inheritance. `PHET_CORE/inherit` was a pre-ES6 implementation of inheritance that is specific to PhET and has been supplanted by `class` and `extends`. `inherit` should
not be used in new code.

The following types are defined using `inherit`, and should be converted  to `class`. 

ModeGraphCanvasNode
StaticModeGraphCanvasNode

**Comment by Hyodar** [comment]
Converted from inherit to class in `ModeGraphCanvasNode` and `StaticModeGraphCanvasNode`.

**Comment by Hyodar** [comment]
Also, did d9d75db to follow the es6 class constructor tag pattern.

**Comment by Hyodar** [comment]
It seems OK, so I'll close it. If necessary, it can be opened again.
