### ISSUE TITLE
misuses of options pattern

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#22]
There is a definite misunderstanding about how to use `options`, which is one of PhET's fundamental design patterns. 

Some examples:

```js
  class OptionsPanel extends Panel {

    /**
     * @param {Object} [panelOptions]
     * @param {Model} model
     * @param {bool} doShowPhases
     */
    constructor( panelOptions, model, doShowPhases = false ) {
```

```js
  class AmpPhaseAccordionBox extends AccordionBox {
    // TODO - comment code

    /**
     * @param {Object} [options]
     * @param {Model} model
     */
    constructor( options, model ) {
```

```js
  class AmpSelectorRectNode extends Rectangle {

    /**
     * @param {Object} [options]
     * @param {Model} model
     */
    constructor( options, model, row, col, ampAxisProperty, maxAmpProperty, gridSizeProperty ) {
```

A description of PHET's "Options and Config" pattern can be found in [PhET Software Design Patterns](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#options-and-config).  Because it is optional, `options` should always be the last parameter.

**Comment by Hyodar** [comment]
Made some changes to the usage of options, though I think some of those classes could still use some cleaning up beyond just changing options to be the last parameter.
I'll take a closer look tomorrow and then close the issue if everything is fine.

**Comment by Hyodar** [comment]
Closing. If necessary, it can be opened again.
