### ISSUE TITLE
property (lowercase) vs Property (uppercase)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#25]
Related to #2 (code review):

> - [ ] Differentiate between `Property` and "property" in comments. They are different things. `Property` is a type in AXON; property is any value associated with a JavaScript object. Often "field" can be used in exchange for "property" which can help with clarity.

There are 3 cases where this is violated, all appear in a comment like this:

`// @private (read-only) Non-property attributes`

**Comment by pixelzoom** [comment]
I went ahead and fixed these. Read for review.

**Comment by Hyodar** [comment]
Thanks for fixing those; I think this is pretty much clear now, so I'll go ahead and close the issue.
