### ISSUE TITLE
sim does not pass lint

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#3]
Related to #2 (code review).

The sim (understandably) does not pass `grunt lint`.  PhET uses ESlint to enforce specific coding standards and avoid JavaScript pitfalls.

This is something that should probably be mentioned more prominently in PhET documentation, maybe in the PhET Development Overview.

**Comment by pixelzoom** [comment]
All of the changes in the above commit are very straightforward.  Let me know if you have questions about any of them.

**Comment by pixelzoom** [comment]
After all of the above lint fixes, the sim now builds with `grunt`, and the built normal-modes_en_phet.html runs fine.

**Comment by tmildemberger** [comment]
The changes are OK, and now we always run `grunt lint` before commiting, so I think this can be closed.
