### ISSUE TITLE
memory testing for brands=phet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#32]
According to the code-review checklist, this is a required GitHub issue.  Do a full memory test for phet brand, and document the results here.

**Comment by pixelzoom** [comment]
Recommended to have QA do this to evaluate whether the sim currently has any leaks.

**Comment by ariel-phet** [comment]
@KatieWoe it would be good to get to this test before the end of the week if possible since it should be straightforward.

**Comment by KatieWoe** [comment]
Here are the test results. The memory is small and rises slowly, so I think everything looks fine.
![normalmemory](https://user-images.githubusercontent.com/41024075/74278984-49ea6880-4cd7-11ea-9132-60f3a73da051.png)

**Comment by pixelzoom** [comment]
Looks good to me! 

@Hyodar @tmildemberger congratulations, the sim has passed memory-leak testing. 

FYI... The process is run the sim in Chrome with `?fuzz`.  You'll hear this referred to as "fuzz testing", and it automatically generates input events that drive the sim.  While this is occurring, you manually take heap snapshots in Chrome.  The first snapshot is taken when the sim starts, and each additional snapshot is at 1-minute intervals. Ideally you want to see the heap size stabilize, where it starts to go up and down a bit.  If the heap size continues to increase, then there's a leak.  In this case, we didn't see stabilization, but the increase is negligible.  So there may be a very small leak somewhere, but it's not worth spending time to find it.  

Closing.
