### ISSUE TITLE
bad type expression {Model} in constructors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#35]
Related to #2 (code review).

This problem exists in the constructors for
OptionsPanel.js, GraphAccordionBox.js, ModeGraphCanvasNode.js, StaticModeGraphCanvasNode.js, AmpSelectorAccordionBox.js, AmpSelectorRectNode.js, 

Type `{Model}` does not exist:

```js
51  * @param {Model} model
```

**Comment by Hyodar** [comment]
Fixed. There are still some parameter issues to be dealt with (#22 and #40), but I plan on fixing them in separate commits to keep things organized.

**Comment by Hyodar** [comment]
Assigning @pixelzoom for review.

**Comment by pixelzoom** [comment]
👍 closing.
