### ISSUE TITLE
rename some view classes to match the UI

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#36]
Related to #2 (code review):

> - [ ] Does the organization and structure of the code make sense? Do the model and view contain types that you would expect (or guess!) by looking at the sim? Do the names of things correspond to the names that you see in the user interface?

While naming of classes generally looks great in this sim, there are a few view classes that could benefit from a rename. 

PhET typically names things based on how they are named in the user interface (UI), and what class of UI component they are.  For example, if there's an accordion box with title "Normal Mode Spectrum", then we would name the class `NormalModeSpectrumAccordionBox`.  

Here's are some suggested renames for this sim:

```
AmpPhaseAccordionBox -> NormalModeSpectrumAccordionBox
GraphAccordionBox -> NormalModesAccordionBox
AmpSelectorAccordionBox -> NormalModeAmplitudesAccordionBox
AmpSelectorRectNode -> AmplitudeSelectorRectangle
```

**Comment by Hyodar** [comment]
Done! Your suggested naming looks a lot better.
