### ISSUE TITLE
review for color-blindness accessibility

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#39]
Related to #2 (code review):

> -[ ]  Is PhetColorScheme used where appropriate? Verify that the sim is not inventing/creating its own colors for things that have been standardized in PhetColorScheme. Identify any colors that might be worth adding to PhetColorScheme.

SpringNodes.js and NormalModesIconFactory.js currently use `stroke: 'red'`.  Should they be using `PhetColorScheme.RED_COLORBLIND`?

**Comment by Hyodar** [comment]
Replaced both of them to `RED_COLORBLIND`.

**Comment by pixelzoom** [comment]
Reopening. Sorry that I wasn't clear on this one.  Colors are typically reviewed by a sim designer, to check for color-blindness accessibility.   And the possible use of PhetColorScheme.RED_COLORBLIND was just one example.   So before you do anything else, a sim designer will review and (possibly) request color changes.

**Comment by Hyodar** [comment]
No problem! We'll be waiting for your review.

**Comment by DianaTavares** [comment]
We have an [updated version of the mockup](https://docs.google.com/document/d/1dzjaCGtnbZ9VaS3qyeNvJiHHS1loUuzLP5__Irqju8k/edit#) for this simulation. I test for colorblind and looks like to colors we are using are appropriate. All the components in the sim can be recognized well. 

![image](https://user-images.githubusercontent.com/26031501/114789051-1e826400-9d48-11eb-9a9b-32569adbda38.png)
![image](https://user-images.githubusercontent.com/26031501/114789489-d152c200-9d48-11eb-8cca-151b8b529dac.png)
![image](https://user-images.githubusercontent.com/26031501/114789517-dadc2a00-9d48-11eb-8670-ea8dde46c25e.png)

Closing this issue.
