### ISSUE TITLE
use PhET code style

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#4]
Related to #2 (code review).

The sim (understandably) does not currently use PhET's code style.  Code-style specifies the code formatting conventions used for code in all PhET repositiories. 

For IntelliJ and WebStorm IDE users, PhET's code style is specified by [phet-idea-codestyle.xml](https://github.com/phetsims/phet-info/blob/master/ide/idea/phet-idea-codestyle.xml), which should be installed as part of your IDE configuration.  For other IDE users, you currently need to be aware of the code-style conventions, and follow them manually.

**Comment by pixelzoom** [comment]
In the above commit, the normal-modes/js/ and all subdirectories were reformatted in WebStorm.

**Comment by tmildemberger** [comment]
We are now following PhET code style, so I think this can be closed.
