### ISSUE TITLE
polish layout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#41]
Noticed during #2 (code review).

The layout of both screens could use some polishing, to:
* make more effective use of negative space
* alleviate some crowding

See screenshots below with `?dev` to show layoutBounds.

<img width="1075" alt="screenshot_109" src="https://user-images.githubusercontent.com/3046552/74186347-ae3df700-4c07-11ea-9d1d-e993e69017a0.png">

<img width="1074" alt="screenshot_110" src="https://user-images.githubusercontent.com/3046552/74186360-b302ab00-4c07-11ea-834f-cfd8dc43ef81.png">

**Comment by ariel-phet** [comment]
Self-assigning

**Comment by ariel-phet** [comment]
@arouinfar and I had an initial discussion today. She will put some mockups in this issue.

**Comment by DianaTavares** [comment]
We have been working on the design of this simulation considering the information in this issue. An updated version of the mock-up can be found in the [design doc](https://docs.google.com/document/d/1dzjaCGtnbZ9VaS3qyeNvJiHHS1loUuzLP5__Irqju8k/edit#), and issues related to the changes that are needed in the dev version are going to be opened.  

Closing this issue.
