### ISSUE TITLE
review design of Speed control, use TimeControlNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#42]
Noticed during #2 (code review), and related to https://github.com/phetsims/scenery-phet/issues/575 (redesign of TimeControlNode).

This sim has a time control, see screenshot below.  It should be using `SCENERY_PHET/TimeControlNode`.   The slider is not part of TimeControlNode.  Is this a necessary part of the design, or could this sim be using radio buttons ala TimeControlNode?

<img width="232" alt="screenshot_111" src="https://user-images.githubusercontent.com/3046552/74186529-096fe980-4c08-11ea-8047-892d39c57a6e.png">

**Comment by pixelzoom** [comment]
FYI, this control was responsible for the failure in #4.   NumberControl is being used for the slider, and that's inappropriate.

**Comment by pixelzoom** [comment]
About this issue over in https://github.com/phetsims/scenery-phet/issues/575#issuecomment-584338869, @arouinfar said:
>  we do not use sliders for sim speed in HTML5 sims. It will be replaced with radio buttons.

**Comment by ariel-phet** [comment]
self-assigning

**Comment by ariel-phet** [comment]
Will be done as part of #41 - closing
