### ISSUE TITLE
remove reset methods that do nothing?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#43]
Related to #2 (code review).

There are a number of `reset` methods that do nothing, and are not called anywhere.  

For example, AmpPhaseAccordionBox.js:

```js
    /**
     * @public
     */
    reset() {
      // NO-OP
    }
```

This isn't hurting anything. But in cases where `reset` (or some other method) does nothing, PhET typically does not implement the method.

**Comment by Hyodar** [comment]
Removed both reset and step methods that did nothing.

**Comment by Hyodar** [comment]
Following the issues workflow:
Assigning @pixelzoom for review.

**Comment by pixelzoom** [comment]
👍 closing.
