### ISSUE TITLE
MassNode visibilityProperty is unnecessary

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#45]
Related to #2 (code review):

In MassNode.js:

```js
      // @public {Property.<boolean>} determines the visibility of the MassNode
      this.visibilityProperty = new DerivedProperty( [ this.mass.visibilityProperty ], function( massVisible ) {
        return massVisible;
      } );
...
      this.visibilityProperty.linkAttribute( this, 'visible' );
```

`this.visibilityProperty` seems unnecessary.   If something is using it, it could use `this.mass.visibilityProperty`. 

This is preferable:

```js
mass.visibilityProperty.linkAttribute( this, 'visible' );
```

**Comment by pixelzoom** [comment]
Also note that if `visibilityProperty` is renamed to `visibleProperty` as recommended in https://github.com/phetsims/normal-modes/issues/46, then it may conflict with PhetioObject `visibleProperty` when this sim is instrumented.

**Comment by Hyodar** [comment]
Removed `visibilityProperty` from `MassNode` in be758f6. 
It really was unnecessary, thanks for pointing it out.

**Comment by Hyodar** [comment]
Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks great, closing.
