### ISSUE TITLE
rename visibilityProperty to visibleProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#46]
Related to #2 (code review).

This sim currently uses `visibilityProperty` throughout.  The PhET naming convention for this Property is `visibleProperty`.  Recommended to change it. 

See Mass.js, Spring.js, MassNode.js, and SpringNode.js for instantiations of `visibilityProperty`.

**Comment by Hyodar** [comment]
Considering the PhetIO conflicts you mentioned on #45, what should we do about renaming those `visibilityProperty`?

**Comment by pixelzoom** [comment]
The conflict with PhET-iO only exists for subclasses of Node, so you can safely rename visibilityProperty to visibleProperty in Mass.js and Spring.js (model classes).

You removed visibilityProperty from MassNode in https://github.com/phetsims/normal-modes/issues/45.   So it's only an issue for SpringNode, where visibilityProperty can be replaced by Property.multilink.

I also discovered 3 model Properties that have this name issue: `springsVisibilityProperty`, `phasesVisibiltyProperty`, and `arrowsVisibileProperty`. 

I took the liberty of making these changes in the above commits.  Please review, and close if this looks OK.

**Comment by Hyodar** [comment]
Understood! 
Looks nice. Closing the issue.
