### ISSUE TITLE
factor out duplicated RadioButtonGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#48]
Related to #2 (code review).

This RadioButtonGroup appears in both screens:

<img width="85" alt="screenshot_112" src="https://user-images.githubusercontent.com/3046552/74189738-2dcec480-4c0e-11ea-8124-bee5aa34188c.png">

The code to create it is duplicated in AmpPhaseAccordionBox and AmpSelectorAccordionBox:

```js
      const horizontalButton = new ArrowNode( 0, 0, iconSize, 0, AXES_ARROW_OPTIONS );
      const verticalButton = new ArrowNode( 0, 0, 0, iconSize, AXES_ARROW_OPTIONS );
      const directionOfMotionRadioButtonGroup = new RadioButtonGroup( model.directionOfMotionProperty, [ {
        value: model.directionOfMotion.HORIZONTAL,
        node: horizontalButton
      }, {
        value: model.directionOfMotion.VERTICAL,
        node: verticalButton
      } ], {
        deselectedLineWidth: 1,
        selectedLineWidth: 1.5,
        cornerRadius: 8,
        deselectedButtonOpacity: 0.35,
        buttonContentXMargin: 8,
        buttonContentYMargin: 8,
        orientation: 'vertical'
      } );
```

Factor this out and encapsulate in a class that extends `RadioButtonGroup`.

**Comment by Hyodar** [comment]
Encapsulated the RadioButtonGroup in a DirectionOfMotionRadioButtonGroup class in the latest commit. 
How do you feel about this class name? I think it only makes sense on the 1D mode, as the masses do move in both directions on 2D mode. Maybe changing DirectionOfMotion to AmplitudeDirection (and all associated names in the same way, 1D and 2D) would be better?

**Comment by pixelzoom** [comment]
@Hyodar renaming `DirectionOfMotion` to `AmplitudeDirection` sounds like a good change.  And the radio button group would then be `AmplitudeDirectionRadioButtonGroup`.

The current implementation of `DirectionOfMotionRadioButtonGroup` looks very nice. You might consider renaming `horizontalButton` and `verticalButton` to something like `horizontalButtonDescription` and `verticalButtonDescription`.  They are not buttons, they are descriptions that RadioButtonGroup will use to instantiate buttons.

**Comment by Hyodar** [comment]
Makes sense. Renamed both `DirectionOfMotion` to `AmplitudeDirection` and the buttons to button descriptors.

**Comment by pixelzoom** [comment]
@Hyodar are you testing your changes with assertions enabled? There's a bug in AmplitudeDirectionRadioButtonGroup (line 45):

```js
45        }, options
46      } );
```

This is causing `merge` to fail with the assertion below.  The `options` are needs to be moved outside down 1 line:

```js
45        }
46      }, options );
```

```
assert.js?bust=1581460495408:22 Uncaught Error: Assertion failed: at least one source expected
    at window.assertions.assertFunction (assert.js?bust=1581460495408:22)
    at merge (merge.js?bust=1581460495492:30)
    at new AmplitudeDirectionRadioButtonGroup (AmplitudeDirectionRadioButtonGroup.js?bust=1581460495492:28)
    at new NormalModeSpectrumAccordionBox (NormalModeSpectrumAccordionBox.js?bust=1581460495492:214)
    at new OneDimensionScreenView (OneDimensionScreenView.js?bust=1581460495492:87)
    at OneDimensionScreen.createView (OneDimensionScreen.js?bust=1581460495492:36)
    at OneDimensionScreen.initializeView (Screen.js?bust=1581460495492:266)
    at Array.<anonymous> (Sim.js?bust=1581460495492:866)
```

It's best to always test with query parameter `ea` to enabled assertions.  And run `grunt lint` to check with ESlint before pushing changes.

**Comment by Hyodar** [comment]
Oh, sorry. My bad. Fixing right away.

**Comment by pixelzoom** [comment]
No problem!  We understand that it takes a little while to get used to our process. And we appreciate your work.

**Comment by Hyodar** [comment]
Probably everything fixed by now.

**Comment by pixelzoom** [comment]
Everything looks great, so I'll close this.
