### ISSUE TITLE
delete package-lock.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#5]
Related to #2 (code review).

package-lock.json was checked in for this sim.    PhET does not use package-lock.json.  Our policy is to prevent it from being generated by running `npm config set save false`.  This will add the following entry in your $HOME/.npmrc file:

```
save=false
```

**Comment by pixelzoom** [comment]
package-lock.json was deleted in the above commit.

**Comment by tmildemberger** [comment]
It seems that the "Getting Started (for Windows)" section of the phet-development-overview.md mentions the need of running `npm config set save false` in step 7, but the "Getting Started (for macOS)" section doesn't. As a Linux user, I didn't read the Windows steps and didn't run the command.

**Comment by pixelzoom** [comment]
Thanks @tmildemberger.  

PhET doesn't officially support Linux, so you're on your own there.  But it's generally a good idea to read through Windows or macOS instructions to get a feel for what needs to be done. 

I also noticed that step 7 was missing from "Getting Started (macOS)" so I just added it.
