### ISSUE TITLE
document viewOrigin

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#53]
Noticed while working on #40.

Both ScreenView subclasses define `viewOrigin`.  The computation of the value is a little complicated, so comments would be nice here. 

OneDimensionScreenView.js:

```js
      const viewOrigin = new Vector2( VIEWBOX_WIDTH / 2 + OneDimensionConstants.SCREEN_VIEW_X_MARGIN + 4,
        ( this.layoutBounds.maxY - 2 * OneDimensionConstants.SCREEN_VIEW_Y_MARGIN - 300 ) / 2 + OneDimensionConstants.SCREEN_VIEW_Y_MARGIN );
```

TwoDimensionsScreenView.js:

```js
      const viewOrigin = new Vector2( ( this.layoutBounds.maxX - 2 * TwoDimensionsConstants.SCREEN_VIEW_X_MARGIN - 420 ) / 2 + TwoDimensionsConstants.SCREEN_VIEW_X_MARGIN,
        ( this.layoutBounds.maxY - 2 * TwoDimensionsConstants.SCREEN_VIEW_Y_MARGIN ) / 2 + TwoDimensionsConstants.SCREEN_VIEW_Y_MARGIN );
```

**Comment by pixelzoom** [comment]
I went ahead and added documentation in the above commits. Please review, feel free to change if the description is inaccurate or you'd prefer something else.

**Comment by Hyodar** [comment]
That's fine with me. What do you think, @tmildemberger?

**Comment by tmildemberger** [comment]
Looks good.

**Comment by Hyodar** [comment]
Since it's already ready for review, I'll go ahead and close it.
