### ISSUE TITLE
use 1-based numbering for modes in tandem names

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#55]
Related to https://github.com/phetsims/tandem/issues/146 and https://github.com/phetsims/normal-modes/issues/17.

In https://github.com/phetsims/tandem/issues/146#issuecomment-601317415, designers requested that we use 1-based numbering for modes.   So the indices that were added in #17 need to be converted to 1-based.

**Comment by pixelzoom** [comment]
Done in the above commits.  This is all a bit hypothetical, since this sim doesn't currently support  brand=phet-io, has had PhET-iO design, and isn't even completed.  

@zepumph would you mind taking a peek?   The relevant code is:

* TwoDimensionalModel, lines 73-124 and 243-262.
* OneDimensionalModel, lines 81-110.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/axon/issues/322, enforcement of "Property" suffix for Property tandem was changed. It's now done for all brands, and I'm glad we made that change.  It exposed this a problem with the tandem naming convention used here:

```
normal-modes : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597491445942/normal-modes/normal-modes_en.html?continuousTest=%7B%22test%22%3A%5B%22normal-modes%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1597491445942%22%2C%22timestamp%22%3A1597492290104%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Property tandem.name must end with Property: normalModes.oneDimensionScreen.model.modeAmplitudeProperties[1]
Error: Assertion failed: Property tandem.name must end with Property: normalModes.oneDimensionScreen.model.modeAmplitudeProperties[1]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597491445942/assert/js/assert.js:22:13)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597491445942/axon/js/Property.js:93:15)
at new NumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597491445942/axon/js/NumberProperty.js:80:5)
at new OneDimensionModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597491445942/normal-modes/js/one-dimension/model/OneDimensionModel.js:86:43)
at OneDimensionScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597491445942/normal-modes/js/one-dimension/OneDimensionScreen.js:36:13)
at OneDimensionScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597491445942/joist/js/Screen.js:285:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597491445942/joist/js/Sim.js:828:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597491445942/joist/js/Sim.js:839:25
id: Bayes Chrome
Snapshot from 8/15/2020, 5:37:25 AM
```

Here's the relevant code in OneDimensionModel.js.  There are 2 other arrays (`this.modePhaseProperties`, `this.modeFrequencyProperties`) with the identical issue.   

```js
    this.modeAmplitudeProperties = new Array( NormalModesConstants.MAX_MASSES_ROW_LEN );
...
for ( let i = 0; i < NormalModesConstants.MAX_MASSES_ROW_LEN; i++ ) {

      // Use 1-based indexing for the tandem names. See https://github.com/phetsims/normal-modes/issues/55
      const tandemIndex = i + 1;

      this.modeAmplitudeProperties[ i ] = new NumberProperty( OneDimensionConstants.INIT_MODE_AMPLITUDE, {
        tandem: tandem.createTandem( `modeAmplitudeProperties[${tandemIndex}]` ),
        range: new Range( OneDimensionConstants.MIN_MODE_AMPLITUDE, Number.POSITIVE_INFINITY )
      } );
  ...
}
```

This issue has been assigned to @zepumph for awhile.  What do you suggest we use for tandem names in cases like this? Should we revert to `'modeAmplitudeProperty${tandemIndex}'`?  `modeAmplitudeProperty[${tandemIndex}]` does not look right to me, since `modeAmplitudeProperty` is not an Array.

**Comment by pixelzoom** [comment]
Ugh... In `TwoDimensionsModel`, there's a similar violation of the "Property" suffix requirement.  But in that case the indexing is 2D:

```
        this.modeXAmplitudeProperties[ i ][ j ] = new NumberProperty( TwoDimensionsConstants.INIT_MODE_AMPLITUDE, {
          tandem: tandem.createTandem( `modeXAmplitudeProperties[${tandemIndex1},${tandemIndex2}]` ),
          range: new Range( TwoDimensionsConstants.MIN_MODE_AMPLITUDE, Number.POSITIVE_INFINITY )
        } );
```

for example `modeXAmplitudeProperties[1,1,]`.    Should we use `modeXAmplitude[1,1]Property`?  If so, should the 1D case be `modeAmplitude[1]Property`?

**Comment by pixelzoom** [comment]
In the above commit, I went with:

* `modeAmplitude1Property` for the 1D case
* `modeXAmplitude[1,1]Property` for the 2D case

I did this to silence the CT error. We should still discuss the general convention that should be used in "array of Property" cases.

**Comment by zepumph** [comment]
Thanks for taking care of this! I actually really like your solution. I'm also happy to have a full discussion.

**Comment by zepumph** [comment]
The relevant doc in https://github.com/phetsims/phet-io/blob/4ec4af88d9cfa3276aece9111a096298750e0834/doc/phet-io-instrumentation-guide.md#phet-io-elements discusses using `element[0,0]` as a pattern. How about the above update? 

>I did this to silence the CT error. We should still discuss the general convention that should be used in "array of Property" cases.

I like your change above, what else would you like to discuss?

**Comment by pixelzoom** [comment]
Doc update looks good. Nothing else to discuss for now.  I suspect that we may need to revisit when designer get their eyeballs on one of there phetioIDs.  But until then, happy to close.
