### ISSUE TITLE
assign responsible developer for normal-modes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#6]
Normal Modes has been added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md).  It is currently unassigned.

**Comment by ariel-phet** [comment]
I have assigned @jonathanolson as the responsible dev for this sim, it seems he will be the best fit if the model needs a bit of troubleshooting, and he is the most familiar with the conversions of Flash sims to HTML5. Considering KP's view of the sim, being less popular, she is fine with the code being in an "OK" but working state, so the publishing and maintenance burden should ideally be small.
