### ISSUE TITLE
identify lead designer

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#61]
From https://github.com/phetsims/normal-modes/issues/57#issuecomment-769311751:
> The designer for this sim hasn't been determined yet, but according to @arouinfar, it will likely be either @arouinfar or @DianaTavares.

And from https://github.com/phetsims/normal-modes/issues/60:
> Review and Finalize Design start=02/01/21 end=02/28/21

Since we're into the timeframe where the design is supposed to be finalized, we need to identify the lead designer.  Assigning to @kathy-phet with high priority.

**Comment by DianaTavares** [comment]
I will be the lead designer for this simulation (Kathy already ask me).
