### ISSUE TITLE
Normal Modes 1.0 prototype

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#64]
This was scheduled at 10/14/21 quarterly planning meeting. 

The QA plan is: 

* dev-lite test (QA + @kathy-phet @ariel-phet @arouinfar)
* RC-lite test

The plan is to fix only things that crash the sim.

**Comment by pixelzoom** [comment]
10/14/21 dev version published for dev-lite testing:
* https://github.com/phetsims/qa/issues/724

**Comment by pixelzoom** [comment]
11/3/21:

* 1.0 branch created using `grunt create-release --branch=1.0`
* no RC published until #77 is completed

**Comment by pixelzoom** [comment]
11/3/2021 RC test started:

* https://github.com/phetsims/qa/issues/733

**Comment by pixelzoom** [comment]
11/11/2021 RC spot-check test started:

* https://github.com/phetsims/qa/issues/737

**Comment by pixelzoom** [comment]
Prototype 1.0.0 has been published: https://phet.colorado.edu/sims/html/normal-modes/latest/normal-modes_en.html

@arouinfar Please:
- [ ] Mark the sim as a prototype on the Admin page.
- [ ] Add the sim to the [HTML5 Prototypes Google Doc](https://docs.google.com/document/d/1d9j8OGO7qPgdL2YvdMeSbztYt7hGXiAL7hAQLXnH-bU/edit).
- [ ] Notify @ariel-phet so that he can announce on social media.

... then close this issue.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! The prototype is now up, and I let @ariel-phet know.
