### ISSUE TITLE
Screenshot for prototype

### ISSUE THREAD

**Issue by arouinfar** [phetsims/normal-modes#65]
For https://github.com/phetsims/qa/issues/724

We can't deploy a sim without a screenshot, so self-assigning.

We'll also use the screenshot on the prototype sims page (added manually post-publication).

**Comment by arouinfar** [comment]
@pixelzoom here's the screenshot for the prototype. There isn't an assets directory to commit it to, so can you take care of it?

[normal-modes-screenshot.png](https://user-images.githubusercontent.com/8419308/139948455-e989e02c-bba4-4c65-930b-61e2dc536095.png)

**Comment by pixelzoom** [comment]
Done, closing.
