### ISSUE TITLE
model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#7]
Related to #2 (code review).  [model.md](https://github.com/phetsims/normal-modes/blob/master/doc/model.md) needs to be written.

> - [ ]  Does model.md adequately describe the model, in terms appropriate for teachers?

**Comment by pixelzoom** [comment]
@ariel-phet asked me to label this one high priority.

PhET currently doesn't have a standard for what's in the model.md file, and it varies dramatically from sim to sim.   The audience for model.md is non-programmers, typically teachers who want to know (at a high level) how the sim's model works.   

A good recent example is https://github.com/phetsims/vector-addition/blob/master/doc/model.md

**Comment by Hyodar** [comment]
The latest commit has the first version of the model description. It took a while because I rewrote some parts a couple of times, but I think it's at least acceptable now.

**Comment by Hyodar** [comment]
@pixelzoom , could you give us some feedback about it before the review? We would really appreciate it.

**Comment by Hyodar** [comment]
Also, I have to take a trip for a few days, so I'll assign @tmildemberger here to make changes if necessary.

**Comment by pixelzoom** [comment]
This looks great.  I made one change in the above commit -- "Options" means something to PhET.  Some sims have an Options choice under the PhET menu, where you can open an Options dialog and set global options.   So I changed "Options" to "Additional Controls".

@tmildemberger If you have additional changes that you'd like reviewed, feel free to assign back to me.  If not, feel free to close this issue.  Thanks!

**Comment by pixelzoom** [comment]
I noticed in #8 (implementation-notes.md) that there is actually an OptionsPanel.  So I took the liberty of renaming it to NormalModesControlPanel.js in the above commit.  I'll also update in implementation-notes.md.

**Comment by Hyodar** [comment]
Yes, that sounds nice. Thanks for reviewing!

Closing the issue.
