### ISSUE TITLE
'Reset All' does not reopen accordion boxes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/normal-modes#72]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari

**Problem description**
https://github.com/phetsims/qa/issues/724

If you close any of the accordion boxes on either screen, pressing 'Reset All' button does not reopen them.

**Steps to reproduce**
1. Close any of the accordion boxes on either screen
2. Press the reset button

**Visuals**
![panels](https://user-images.githubusercontent.com/87318828/139861630-88cb6a72-78cb-4b80-a67d-8fa81717b6f7.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Normal Modes‬
URL: https://phet-dev.colorado.edu/html/normal-modes/1.0.0-dev.5/phet/normal-modes_en_phet.html
Version: 1.0.0-dev.5 2021-11-01 21:43:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Language: en-US
Window: 1199x701
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi, reproduced.    I've adjusted the title and report to indicate "accordion box". Panels do not expand/collapse.

**Comment by pixelzoom** [comment]
Inspecting the code, I see that none of the accordion boxes are provided with option `expandedProperty`.   So they create their own `expandedProperty`, which needs to be reset.

**Comment by Nancy-Salpepi** [comment]
Looks good.
