### ISSUE TITLE
Rendering order of Springs, Masses and Accordion Box inconsistent 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/normal-modes#74]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari

**Problem description**
https://github.com/phetsims/qa/issues/724

In the 2 Dimensions Screen, the Springs move behind the Normal Mode Amplitudes accordion box while the Masses move in front. 

**Steps to Reproduce**
1. Select the 2 Dimensions Screen 
2. Increase the Number of Masses to 36
3. Select the Horizontal radio button
4. Turn on all of the modes by pressing all of the buttons
5. Change the sim speed to slow

**Visuals**
![springsbehind](https://user-images.githubusercontent.com/87318828/139890331-e07e6f72-1b86-4dc5-90e8-76f7ac8c91d6.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Normal Modes‬
URL: https://phet-dev.colorado.edu/html/normal-modes/1.0.0-dev.5/phet/normal-modes_en_phet.html
Version: 1.0.0-dev.5 2021-11-01 21:43:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Language: en-US
Window: 1199x701
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Looking at the layering order (in the ScreenView subclasses) I can see that it's a little odd, to say the least. 

@arouinfar @ariel-phet would you like the masses and springs to be in front of or behind the control panels?

**Comment by ariel-phet** [comment]
@pixelzoom in front would probably be easiest and will be fine.

**Comment by pixelzoom** [comment]
@ariel-phet I actually think that masses/spring BEHIND controls would be better. We typically do not want things in front of controls, and that's especially relevant since this sim can paused/stepped. Behind would also be consistent with recent (similar) decisions that were made in geometric-optics. 

Are you OK with that?

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet on Slack. He pointed out that while behind is more consistent with modern PhET sims, in front is more consistent with the legacy (Flash) version.  So will go with legacy behavior for the prototype, and can revisit for final version.

**Comment by pixelzoom** [comment]
In the above commits, I adjusted the rendering order for both screen, so that masses and springs are in front of controls.  In the 'One Dimension' screen, this is relevant for horizontal movement.

Back to @Nancy-Salpepi to verify. Close if it looks OK.

**Comment by Nancy-Salpepi** [comment]
Masses and springs are now in front of controls.
<img width="417" alt="Screen Shot 2021-11-02 at 2 58 23 PM" src="https://user-images.githubusercontent.com/87318828/139928061-5d869faf-b70c-4421-8213-b225a682130a.png">

**Comment by arouinfar** [comment]
For the record, I think keeping the masses in front of the panels is the right call for the prototype. When it comes time to complete the sim, we should constrain the displacement of the masses which will likely reduce the amount of overlap that is possible.
