### ISSUE TITLE
Max widths needed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/normal-modes#76]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/724. When strings are either doubled or long, the control boxes can overlap with the play areas.

**Visuals**
<img width="959" alt="needed2" src="https://user-images.githubusercontent.com/41024075/139919072-f5e64f73-5e35-4824-9ed8-d97d1b1633e4.png">
<img width="953" alt="maxwidthsneeded" src="https://user-images.githubusercontent.com/41024075/139919074-d2f4fb54-6713-4d4a-99ea-dd3cb72d049c.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/normal-modes/1.0.0-dev.5/phet/normal-modes_en_phet.html?stringTest=long
Version: 1.0.0-dev.5 2021-11-01 21:43:06 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This also leads to object going off screen if the window isn't wide enough.
<img width="554" alt="cutoff" src="https://user-images.githubusercontent.com/41024075/139919538-09a9ae34-7cb7-4065-957f-325f5464ea85.png">

**Comment by arouinfar** [comment]
> I recommend that we close this issue. @arouinfar do you agree?

Sounds good to me, closing.
