### ISSUE TITLE
implementation-notes.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#8]
Related to #2 (code review). [implementation-notes.md](https://github.com/phetsims/normal-modes/blob/master/doc/implementation-notes.md) needs to be written.

> - [ ] Does implementation-notes.md adequately describe the implementation, with an overview that will be useful to future maintainers?

**Comment by pixelzoom** [comment]
@ariel-phet asked me to label this one high priority.

PhET currently doesn't have a standard for what's in the model.md file, and it varies dramatically from sim to sim. The audience for implementation-notes.md is programmers who may need to maintain or enhance the sim.  At a minimum, it should describe the overall architecture, identify where specific design patterns are used, and describe memory management.

A good recent example is: https://github.com/phetsims/vector-addition/blob/master/doc/implementation-notes.md

After implementation-notes.md has been written, it should be reviewed by a programmer.

**Comment by Hyodar** [comment]
Added a simple `implementation-notes` on 75d6218.

@pixelzoom, could you take a look at it and `model.md`? As the documentation varies a lot from sim to sim, it would be good if you could give us some feedback.

**Comment by pixelzoom** [comment]
Sorry, I somehow missed the GitHub notification about this. Best to assign to me when you want me to review something.  I'll try review this today.

**Comment by Hyodar** [comment]
No problem, thanks!

**Comment by pixelzoom** [comment]
I made a couple of minor changes in the above commits, but overall this looks really great - well done!   Feel free to close this issue if you're also happy with it.

**Comment by Hyodar** [comment]
Thanks! 
I'm also happy with it; we only need to remember to change the document in case anything described there is changed.

Closing the issue.
