### ISSUE TITLE
Unclear what the result should be when adjusting amplitudes using multitouch

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/normal-modes#81]
**Test device**
iPad Air 2

**Operating System**
15.1

**Problem description**
https://github.com/phetsims/qa/issues/733

This is related to https://github.com/phetsims/normal-modes/issues/79
When using multitouch to adjust amplitudes, I was unsure whether the values displayed were correct. 

**Steps to reproduce**
1. On the 1 dimension screen, use one finger to hold a mass in place while increasing the values of all amplitudes using the sliders.
2. Let go of the mass--the amplitude values change. 

**Visuals**

https://user-images.githubusercontent.com/87318828/140972999-b986c09f-1afe-48a0-8bd4-4e38819d3945.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Normal Modes‬
URL: https://phet-dev.colorado.edu/html/normal-modes/1.0.0-rc.1/phet/normal-modes_all_phet.html
Version: 1.0.0-rc.1 2021-11-03 19:33:33 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Language: en-US
Window: 1313x633
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
The multitouch problem is tracked in https://github.com/phetsims/normal-modes/issues/79.  It will not be addressed for the prototype, and longterm multitouch requirements need to be specificed in  and https://github.com/phetsims/normal-modes/issues/80.  For example, what is the desired behavior when dragging a mass and changing its amplitude slider? I have no idea.

@arouinfar As long as the sim does not crash, I recommend closing this as "won't fix".

**Comment by arouinfar** [comment]
Nice find @Nancy-Salpepi. I agree with @pixelzoom that multitouch is beyond the scope of the prototype. Closing as won't fix.
