### ISSUE TITLE
Normal Modes accordion box outside dev bounds on iPad

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/normal-modes#82]
**Test device**
iPad Air 2

**Operating System**
15.0

**Problem description**
https://github.com/phetsims/qa/issues/733

This is a very minor issue. When the iPad is held horizontally the bottom of the Normal Modes accordion box is outside of dev bounds.

**Steps to reproduce**
1. Hold the iPad horizontally
2. On the One Dimension Screen, increase the number of masses to 10

**Visuals**

<img width="457" alt="Screen Shot 2021-11-09 at 12 37 56 PM" src="https://user-images.githubusercontent.com/87318828/140975817-100b2be4-373c-41bc-b5e3-8ca5892dba40.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Normal Modes‬
URL: https://phet-dev.colorado.edu/html/normal-modes/1.0.0-rc.1/phet/normal-modes_all_phet.html
Version: 1.0.0-rc.1 2021-11-03 19:33:33 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Language: en-US
Window: 1313x633
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Reproduced on iPad6.  That very odd, I guess the font sizes must be significantly taller on iOS.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branches in the above commit. 

@Nancy-Salpepi please verify in master. If it looks OK, please change the label to "fixed-awaiting-deploy".

**Comment by Nancy-Salpepi** [comment]
Looks good on master.

**Comment by pixelzoom** [comment]
To verify in 1.0.0-rc.2:

1. Run the sim on iPad
2. Go to One Dimension screen
3. Expand the "Normal Modes" accordion box
4. Verify that everything is inside the dev bounds

**Comment by Nancy-Salpepi** [comment]
Everything is inside dev bounds.
