### ISSUE TITLE
Mass position not reset using multitouch

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/normal-modes#83]
**Test device**
iPad Air 2

**Operating System**
15.1

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/733

Related to https://github.com/phetsims/normal-modes/issues/79

On the iPad, when holding a mass with one finger, and changing the Number of Masses using the slider--the location of the original mass seems to reset. Upon lifting your finger you can see that is not actually the case. 

**Steps to reproduce**
1. On the One Dimension Screen, change the Number of Masses to 1
2. Move the mass from its original position and hold it there
3. With another finger, increase and decrease the Number of Masses so you end up back at 1
4. Remove your finger

**Visuals**

https://user-images.githubusercontent.com/87318828/140982125-05b4a0ec-c28e-45a6-891b-93657b3e65b3.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Normal Modes‬
URL: https://phet-dev.colorado.edu/html/normal-modes/1.0.0-rc.1/phet/normal-modes_all_phet.html
Version: 1.0.0-rc.1 2021-11-03 19:33:33 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Language: en-US
Window: 1313x633
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
When the number of masses is changed, all drag interactions should be interrupted.  That's clearly not happening here.  I can probably add a bandaid.  But this needs to be addressed in the future by #80 (Multitouch support).

**Comment by pixelzoom** [comment]
In the above commits to master and 1.0, dragging of masses is now interrupted when **Number of Masses** is changed. 

@Nancy-Salpepi please review in master. Change the label to fixed-awaiting-deploy if it looks OK.

**Comment by Nancy-Salpepi** [comment]
Looks good in master.

**Comment by pixelzoom** [comment]
To verify in 1.0.0-rc.2:

1. Run the sim on iPad
2. Go to the One Dimension screen
3. Drag a mass with one finger, do not release.
4. Drag a different mass with another finger, verify that the first mass drag is interrupted.
5. Repeat steps 3 & 4 for the Two Dimensions screen.

**Comment by Nancy-Salpepi** [comment]
The first mass is no longer held in place once a second mass is dragged.
