### ISSUE TITLE
QA credits for 1.0 (prototype) release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#85]
For https://github.com/phetsims/qa/issues/733

I discovered that this sim currently has no QA credits.  @KatieWoe who should be added?

**Comment by KatieWoe** [comment]
Sorry about that. Nancy Salpepi, Emily Miller, and myself should be added.

**Comment by KatieWoe** [comment]
No updates for QA for RC.2

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. We're ready to publish the 1.0 prototype, so I'll close this issue.
