### ISSUE TITLE
Possible debug error

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/normal-modes#86]
For https://github.com/phetsims/qa/issues/737. While running a fuzz test on the debug version of the sim, this console error appeared. I'm not sure what caused it and the sim kept running.
<img width="959" alt="debugerror" src="https://user-images.githubusercontent.com/41024075/141839476-b83f6ed5-b73a-463d-9bd3-20453586dc94.png">

**Comment by KatieWoe** [comment]
May be related to https://github.com/phetsims/normal-modes/issues/56

**Comment by pixelzoom** [comment]
Yes, this is a duplicate of https://github.com/phetsims/normal-modes/issues/56.  We're not addressing that issue for the prototype.  Closing.
