### ISSUE TITLE
.png files at top-level of repository

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/normal-modes#9]
Related to #2 (code review).

There are several .png files at the top level of the repository, and they are not used by the sim:

```
better_springs.png
hidden_panel.png
new_buttons.png
paused_and_arrows.png
wave_icons.png
wavy_things.png
```

Can these be deleted? Or moved somewhere else?

**Comment by Hyodar** [comment]
Those .png files were all used in `todo.md`, a TODO checklist that we used during development. I removed both the images and `todo.md`.

**Comment by Hyodar** [comment]
Assigning @pixelzoom for review.

**Comment by pixelzoom** [comment]
👍 closing.
